"""Configurable STB/ASTB simulation; every reported budget counts actual responses.

ASTB geometry uses Decimal arithmetic in coordinates (x-left)/R.  Truth is used
only by the observation simulator, error/coverage reporting, and a numerical
sign-certification check.  The estimator is centered at the initial midpoint.
If geometry is inadequately resolved, the same seeded experiment restarts at
twice the precision.  No statistical stopping or minimum-width rule is added.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
import pickle
import sys
import time
from decimal import Decimal, localcontext
from fractions import Fraction
from pathlib import Path

import numpy as np

from revision_kernels import scan_test

# Exact STB jump brackets can have more than 4,300 decimal digits. These are
# trusted integers generated by this simulation, not untrusted parsed requests.
if hasattr(sys, "set_int_max_str_digits"):
    sys.set_int_max_str_digits(0)

SEED = 42
REVISION_DOMAIN = 20261009
SCHEMA_VERSION = "stb-astb-v2"
GRID = tuple(10**k for k in range(2, 10))
BLOCK = 262144
TEST_BLOCK = 16384
CHECKPOINT_SECONDS = 30.0
DEFAULT_PRECISION = 40
MAX_PRECISION = 1_048_576
FIT_PRECISION = 64
FIT_AUDIT_PRECISION = 128


class PrecisionRequired(ArithmeticError):
    """A deterministic arithmetic guard requires a higher-precision restart."""


def _fraction(value):
    if isinstance(value, Fraction):
        return value
    return Fraction(str(value))


def _get_fraction(cfg, *names, default=None):
    for key in names:
        if key in cfg:
            return _fraction(cfg[key])
    if default is None:
        raise KeyError(names)
    return _fraction(default)


def validate_config(cfg):
    """Resolve exact geometry while preserving the caller's setting identity."""
    left = _get_fraction(cfg, "left_fraction", "left_exact", "left", default=0)
    right = _get_fraction(cfg, "right_fraction", "right_exact", "right", default=1)
    theta = _get_fraction(cfg, "theta_fraction", "theta_exact", "root", "theta")
    if not left < theta < right:
        raise ValueError("The root must lie strictly inside the initial interval.")
    amplitude = float(cfg.get("A", cfg.get("amplitude", cfg.get("signal", 1.0))))
    sigma = float(cfg["sigma"])
    v = float(cfg.get("v", sigma))
    gamma = float(cfg["gamma"])
    delta = float(cfg.get("delta", .05))
    if gamma not in (-1., 0., 1., 2., 3.):
        raise ValueError("Supported gamma values: -1 (e+2e^3), 0, 1, 2, 3.")
    if not (amplitude > 0 and sigma > 0 and v >= sigma and 0 < delta < 1):
        raise ValueError("Require A>0, sigma>0, Gaussian proxy v>=sigma, 0<delta<1.")
    if not all(map(math.isfinite, (amplitude, sigma, v, delta))):
        raise ValueError("Non-finite simulation parameter.")
    return dict(left=left, right=right, theta=theta, R=right-left,
                A=amplitude, sigma=sigma, v=v, gamma=gamma, delta=delta,
                setting=int(cfg["setting"]))


def seed_keys(phase, method, setting, n, rep, substream=0):
    return [SEED, REVISION_DOMAIN, int(phase), int(method), int(setting),
            int(n), int(rep), int(substream)]


def _rng(keys):
    return np.random.default_rng(np.random.SeedSequence(keys))


def _identity(cfg, kind, phase, rep, budgets):
    payload = dict(schema=SCHEMA_VERSION, config=cfg, kind=kind, phase=int(phase),
                   rep=int(rep), budgets=[int(n) for n in budgets])
    packed = json.dumps(payload, sort_keys=True, default=str, separators=(",", ":"))
    return hashlib.sha256(packed.encode()).hexdigest()


def _load(checkpoint, identity):
    if checkpoint is None or not Path(checkpoint).exists():
        return None
    with Path(checkpoint).open("rb") as handle:
        payload = pickle.load(handle)
    if payload.get("identity") != identity or payload.get("schema") != SCHEMA_VERSION:
        raise ValueError(f"Checkpoint belongs to a different experiment: {checkpoint}")
    return payload["state"]


def _save(checkpoint, identity, state):
    if checkpoint is None:
        return
    path = Path(checkpoint)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + f".{os.getpid()}.tmp")
    with temporary.open("wb") as handle:
        pickle.dump(dict(schema=SCHEMA_VERSION, identity=identity, state=state),
                    handle, protocol=pickle.HIGHEST_PROTOCOL)
    os.replace(temporary, path)


class _NoiseStream:
    """Observation-indexed noise: unconsumed block tails are retained."""
    def __init__(self, keys, sigma, saved=None):
        self.gen = _rng(keys)
        self.sigma = sigma
        self.buffer = np.empty(0)
        self.offset = 0
        self.generated = 0
        if saved is not None:
            self.gen.bit_generator.state = saved["rng"]
            self.buffer = saved["buffer"]
            self.offset = saved["offset"]
            self.generated = saved["generated"]

    def peek(self, limit):
        if self.offset == len(self.buffer):
            self.buffer = self.gen.normal(0., self.sigma, BLOCK)
            self.offset = 0
            self.generated += BLOCK
        return self.buffer[self.offset:min(len(self.buffer), self.offset + int(limit))]

    def consume(self, count):
        self.offset += int(count)

    def snapshot(self):
        return dict(rng=self.gen.bit_generator.state, buffer=self.buffer,
                    offset=self.offset, generated=self.generated)


def _float_fraction(value):
    try:
        return float(value)
    except OverflowError:
        return math.copysign(math.inf, value.numerator)


def _log_fraction(value):
    if not value:
        return -math.inf
    return (math.log(abs(value.numerator))-math.log(value.denominator))/math.log(10.)


def _decimal_fraction(value):
    return Decimal(value.numerator) / Decimal(value.denominator)


def _df(value):
    """The exact decimal representation of a binary64 aggregate."""
    return Decimal.from_float(float(value))


def _float_decimal(value):
    return float(value)


def _log_decimal(value):
    if not value:
        return -math.inf
    # Logs are reporting values only. Avoid a thousands-digit transcendental
    # calculation when the result will be returned as binary64.
    digits, exponent = value.as_tuple().digits, value.as_tuple().exponent
    leading_digits = digits[:17]
    leading = int("".join(map(str, leading_digits))) / 10**(len(leading_digits)-1)
    return len(digits)+exponent-1+math.log10(leading)


def _signal_fraction(error, cfg):
    if cfg["gamma"] == 0:
        return cfg["A"] * (1. if error > 0 else -1. if error < 0 else 0.)
    e = float(error)
    if cfg["gamma"] == -1:
        return cfg["A"] * (e + 2.*e**3)
    return cfg["A"] * math.copysign(abs(e)**int(cfg["gamma"]), e)


def _signal_decimal(error, cfg):
    if cfg["gamma"] == 0:
        return cfg["A"] * (1. if error > 0 else -1. if error < 0 else 0.)
    # Converting once after the power also protects the sign at tiny positions.
    if cfg["gamma"] == -1:
        value = error + 2 * error**3
    else:
        value = abs(error)**int(cfg["gamma"])
        if error < 0:
            value = -value
    return cfg["A"] * float(value)


def run_stb_task(cfg, rep, checkpoint=None, grid=GRID, phase=210):
    """One continuing exact-geometry STB run, observed at every supplied budget."""
    model = validate_config(cfg)
    grid = tuple(map(int, grid))
    if not grid or grid[0] < 1 or any(b <= a for a, b in zip(grid, grid[1:])):
        raise ValueError("Budgets must be positive and strictly increasing.")
    identity = _identity(cfg, "stb", phase, rep, grid)
    state = _load(checkpoint, identity)
    mid = (model["left"] + model["right"])/2
    if state is None:
        state = dict(q=0, l=model["left"], r=model["right"], x=mid, t=1,
                     j=0, S=0., best_count=0, best_x=mid, covered=True, rows=[],
                     elapsed_seconds=0., noise=None)
    keys = seed_keys(phase, 30, model["setting"], 0, rep)
    noise = _NoiseStream(keys, model["sigma"], state["noise"])
    K = max(2, math.ceil(math.log2(4/model["delta"])))
    last_save = time.monotonic()

    def save():
        nonlocal last_save
        now = time.monotonic()
        state["elapsed_seconds"] += now-last_save
        last_save = now
        state["noise"] = noise.snapshot()
        _save(checkpoint, identity, state)

    for budget in grid:
        if state["rows"] and state["rows"][-1]["n"] >= budget:
            continue
        while state["q"] < budget:
            eps = noise.peek(min(TEST_BLOCK, budget-state["q"]))
            fx = _signal_fraction(state["x"]-model["theta"], model)
            used, total, crossed = scan_test(eps, fx, state["S"], state["j"],
                                            state["t"], K, model["v"])
            used = int(used)
            noise.consume(used)
            state["q"] += used
            state["j"] += used
            state["S"] = float(total)
            if crossed:
                if state["j"] > state["best_count"]:
                    state["best_count"], state["best_x"] = state["j"], state["x"]
                state["r" if total > 0 else "l"] = state["x"]
                state["covered"] &= state["l"] <= model["theta"] <= state["r"]
                state["t"] += 1
                state["j"], state["S"] = 0, 0.
                state["x"] = (state["l"]+state["r"])/2
            if time.monotonic()-last_save >= CHECKPOINT_SECONDS:
                save()
        winner = state["x"] if state["j"] > state["best_count"] else state["best_x"]
        estimate = max(state["l"], min(state["r"], winner))
        error = abs(estimate-model["theta"])
        width = state["r"]-state["l"]
        assert state["q"] == budget
        state["rows"].append(dict(n=budget, q=budget, setting=model["setting"],
            replicate=int(rep), estimate=float(estimate), error=_float_fraction(error),
            length=_float_fraction(width), log10_error=_log_fraction(error),
            log10_length=_log_fraction(width), exact_estimate=str(estimate),
            exact_error=str(error), exact_length=str(width),
            pointwise=int(state["l"] <= model["theta"] <= state["r"]),
            simultaneous=int(state["covered"]), covered=int(state["covered"]),
            stages=state["t"]-1, unfinished=state["j"], K=K,
            tests=budget, extra=0, fallback=0, precision="exact rational geometry",
            status="complete"))
        save()
    save()
    return dict(q=state["q"], rows=state["rows"], seed_keys=keys,
                runtime_seconds=state["elapsed_seconds"],
                computational_observations=state["q"],
                generated_normal_values=noise.generated, identity=identity)


def _initial_astb(precision, previous=None):
    previous = previous or {}
    return dict(q=0, t=1, l=Decimal(0), r=Decimal(1), fl=None, fr=None,
        phase="position", j=0, S=0., mx=Decimal(0), my=Decimal(0),
        D=Decimal(0), Cxy=Decimal(0), Cyy=Decimal(0), noise_sum=Decimal(0),
        tests=0, extra=0, covered=True, last_phase=0, noise=None, weights=None,
        precision=int(precision), precision_restarts=previous.get("precision_restarts", []),
        fit_audit=dict(mx=Decimal(0), my=Decimal(0), D=Decimal(0),
                       Cxy=Decimal(0), Cyy=Decimal(0)),
        retry_observations=previous.get("retry_observations", 0),
        retry_generated=previous.get("retry_generated", 0),
        elapsed_seconds=previous.get("elapsed_seconds", 0.))


def _geometry_bound(stage, precision):
    # z endpoints remain in [0,1]. Each convex update has at most a handful
    # of rounded operations; their absolute errors accumulate at most linearly.
    # 32*(t+1)*10^(1-p) conservatively covers these operations and root division.
    return Decimal(32*(int(stage)+1)) * Decimal(10)**(1-int(precision))


def _check_position(state, root_coordinate):
    bound = _geometry_bound(state["t"], state["precision"])
    width = state["r"]-state["l"]
    if width <= Decimal("1e18")*bound:
        raise PrecisionRequired("interval width has fewer than 18 guard digits")
    if abs(state["z"]-root_coordinate) <= Decimal("1e12")*bound:
        raise PrecisionRequired("observation sign has fewer than 12 guard digits")
    if not state["l"] < state["z"] < state["r"]:
        raise PrecisionRequired("weighted position is not strictly interior")


def _merge_moments(moments, z, mean, within, q, count, precision):
    with localcontext() as context:
        context.prec = precision
        total = q+count
        x = (+z)-Decimal(".5")  # known initial midpoint, never the root
        dx, dy = x-moments["mx"], mean-moments["my"]
        weight = Decimal(q)*Decimal(count)/Decimal(total)
        moments["D"] += weight*dx*dx
        moments["Cxy"] += weight*dx*dy
        moments["Cyy"] += within+weight*dy*dy
        moments["mx"] += Decimal(count)/Decimal(total)*dx
        moments["my"] += Decimal(count)/Decimal(total)*dy


def _merge_fit(state, z, fx, eps):
    """Merge every response into centered OLS and a higher-precision audit.

    Geometry precision may be thousands of digits at jumps. OLS retains the
    informative historical locations, so its arithmetic is evaluated separately
    at 64 and 128 digits. Both receive identical float64 response aggregates.
    """
    count = len(eps)
    if not count:
        return
    y = fx + eps
    mean_float = float(np.mean(y))
    mean = _df(mean_float)
    within = _df(float(np.sum((y-mean_float)**2)))
    q = state["q"]
    _merge_moments(state, z, mean, within, q, count, FIT_PRECISION)
    _merge_moments(state["fit_audit"], z, mean, within, q, count, FIT_AUDIT_PRECISION)
    with localcontext() as context:
        context.prec = FIT_AUDIT_PRECISION
        state["noise_sum"] += _df(float(np.sum(eps)))
    state["q"] = q+count


def _fit_values(moments, model, n, precision):
    with localcontext() as context:
        context.prec = precision
        left, R = _decimal_fraction(model["left"]), _decimal_fraction(model["R"])
        midpoint = left+R/2
        fallback = moments["D"] <= 0 or moments["Cxy"] <= 0
        if fallback:
            slope = Decimal(0) if moments["D"] <= 0 else moments["Cxy"]/moments["D"]/R
            estimate, noise_var, variance = midpoint, Decimal(0), Decimal(0)
        else:
            slope_u = moments["Cxy"]/moments["D"]
            slope = slope_u/R
            estimate = midpoint+R*(moments["mx"]-moments["my"]/slope_u)
            residual = moments["Cyy"]-moments["Cxy"]**2/moments["D"]
            noise_var = max(Decimal(0), residual/Decimal(n))
            variance = noise_var/slope**2
        return dict(fallback=fallback, slope=slope, estimate=estimate,
                    noise_var=noise_var, variance=variance)


def _astb_result(state, model, n, rep, K, noise_keys, weight_keys, identity):
    left, R = _decimal_fraction(model["left"]), _decimal_fraction(model["R"])
    theta = _decimal_fraction(model["theta"])
    fitted = _fit_values(state, model, n, FIT_PRECISION)
    audited = _fit_values(state["fit_audit"], model, n, FIT_AUDIT_PRECISION)
    fallback, slope, estimate, noise_var, variance = (fitted[k] for k in (
        "fallback", "slope", "estimate", "noise_var", "variance"))
    with localcontext() as context:
        context.prec = FIT_AUDIT_PRECISION
        discrepancy = abs(estimate-audited["estimate"])/_decimal_fraction(model["R"])
        relative = {key: abs(fitted[key]-audited[key])/max(abs(audited[key]), Decimal("1e-100"))
                    for key in ("slope", "noise_var", "variance")}
        fit_audit = dict(passed=bool(fallback == audited["fallback"] and discrepancy < Decimal("1e-40")
                                    and all(x < Decimal("1e-35") for x in relative.values())),
            estimate_discrepancy_in_interval_widths=str(discrepancy),
            relative_discrepancies={key: str(value) for key, value in relative.items()},
            primary_digits=FIT_PRECISION, audit_digits=FIT_AUDIT_PRECISION)
    error = abs(estimate-theta)
    width = R*(state["r"]-state["l"])
    error_signed = estimate-theta
    zscore = error_signed*Decimal(n).sqrt()
    beta = model["A"] if model["gamma"] in (1., -1.) else None
    result = dict(n=int(n), q=state["q"], setting=model["setting"], replicate=int(rep),
        theta=float(model["theta"]), sigma=model["sigma"], beta=beta,
        estimate=float(estimate), error=float(error), length=float(width),
        estimate_decimal=str(estimate), error_decimal=str(error), length_decimal=str(width),
        log10_error=_log_decimal(error), log10_length=_log_decimal(width),
        slope=float(slope), D=float(state["D"]*R**2),
        variance_estimate=float(variance), noise_variance=float(noise_var),
        tests=state["tests"], extra=state["extra"], stages=state["t"]-1,
        unfinished=state["j"] if state["phase"] == "test" else 0,
        K=K, fallback=int(fallback), covered=int(state["covered"]),
        simultaneous=int(state["covered"]), last_phase=state["last_phase"],
        pointwise=int(state["l"] <= _decimal_fraction((model["theta"]-model["left"])/model["R"]) <= state["r"]),
        noise_sum=float(state["noise_sum"]), status="complete",
        precision="adaptive Decimal geometry; 64-digit grouped OLS with 128-digit audit",
        precision_digits=state["precision"], fit_precision_audit=fit_audit,
        precision_restarts=state["precision_restarts"],
        geometry_roundoff_bound=str(_geometry_bound(state["t"], state["precision"])),
        retry_observations=state["retry_observations"],
        computational_observations=state["retry_observations"]+state["q"],
        generated_normal_values=state["retry_generated"]+state["noise"]["generated"],
        runtime_seconds=state["elapsed_seconds"], noise_seed_keys=noise_keys,
        weight_seed_keys=weight_keys, identity=identity)
    if beta is not None:
        result.update(normalized=float(zscore),
            standardized=float(zscore)*beta/model["sigma"],
            studentized=float(zscore)/math.sqrt(float(variance)) if variance > 0 else 0.,
            linear_remainder=float(zscore+state["noise_sum"]/(Decimal(str(beta))*Decimal(n).sqrt())),
            inference_scope="positive-slope CLT")
    else:
        result.update(normalized=None, standardized=None, studentized=None,
                      linear_remainder=None, inference_scope="empirical error only")
    assert result["q"] == n == result["tests"]+result["extra"]
    if not fit_audit["passed"]:
        result.update(status="fit_precision_failure", failure_reason="OLS arithmetic audit failed",
                      estimate=None, error=None, log10_error=None)
    return result


def run_astb_task(cfg, n, rep, checkpoint=None, phase=210):
    """One independently budgeted ASTB run, with deterministic precision retries."""
    model = validate_config(cfg)
    n = int(n)
    if n < 1:
        raise ValueError("Budget must be positive.")
    identity = _identity(cfg, "astb", phase, rep, [n])
    initial_precision = int(cfg.get("initial_precision_digits", DEFAULT_PRECISION))
    max_precision = int(cfg.get("max_precision_digits", MAX_PRECISION))
    if not 24 <= initial_precision <= max_precision:
        raise ValueError("Require 24<=initial_precision_digits<=max_precision_digits.")
    state = _load(checkpoint, identity) or _initial_astb(initial_precision)
    if "terminal_failure_result" in state:
        return state["terminal_failure_result"]
    noise_keys = seed_keys(phase, 40, model["setting"], n, rep, 0)
    weight_keys = seed_keys(phase, 40, model["setting"], n, rep, 1)
    K = max(2, math.ceil(math.log2(4/model["delta"]))) + math.ceil(math.log(math.log(n+math.exp(math.e))))

    while True:
        noise = _NoiseStream(noise_keys, model["sigma"], state["noise"])
        weights = _rng(weight_keys)
        if state["weights"] is not None:
            weights.bit_generator.state = state["weights"]
        last_save = time.monotonic()

        def save():
            nonlocal last_save
            now = time.monotonic()
            state["elapsed_seconds"] += now-last_save
            last_save = now
            state["noise"] = noise.snapshot()
            state["weights"] = weights.bit_generator.state
            _save(checkpoint, identity, state)

        with localcontext() as context:
            context.prec = state["precision"]
            # Geometry may legitimately be far below binary64/subnormal range.
            context.Emin, context.Emax = -999999999, 999999999
            root_coordinate = _decimal_fraction((model["theta"]-model["left"])/model["R"])
            R = _decimal_fraction(model["R"])
            try:
                while state["q"] < n:
                    if state["phase"] == "position":
                        w = .5
                        if state["fl"] is not None and state["fr"] is not None and state["fl"] < 0 < state["fr"]:
                            w = -state["fl"]/(state["fr"]-state["fl"])
                        w = min(5/8, max(3/8, w))+weights.uniform(-1/8, 1/8)
                        # This exact binary64 weight is used at every precision.
                        w_decimal = _df(w)
                        state["z"] = (1-w_decimal)*state["l"]+w_decimal*state["r"]
                        _check_position(state, root_coordinate)
                        state["fx"] = _signal_decimal(R*(state["z"]-root_coordinate), model)
                        state["j"], state["S"], state["phase"] = 0, 0., "test"
                    if state["phase"] == "test":
                        eps = noise.peek(min(TEST_BLOCK, n-state["q"]))
                        used, total, crossed = scan_test(eps, state["fx"], state["S"], state["j"], state["t"], K, model["v"])
                        used = int(used)
                        _merge_fit(state, state["z"], state["fx"], eps[:used])
                        noise.consume(used)
                        state["j"] += used
                        state["tests"] += used
                        state["S"] = float(total)
                        state["last_phase"] = 0
                        if crossed:
                            state["positive"] = total > 0
                            state["r" if state["positive"] else "l"] = state["z"]
                            state["covered"] &= state["l"] <= root_coordinate <= state["r"]
                            state["extra_target"] = min(state["j"], n-state["q"])
                            state["extra_done"], state["phase"] = 0, "extra"
                    if state["phase"] == "extra":
                        remaining = state["extra_target"]-state["extra_done"]
                        if remaining:
                            eps = noise.peek(min(BLOCK, remaining))
                            count = len(eps)
                            _merge_fit(state, state["z"], state["fx"], eps)
                            noise.consume(count)
                            state["S"] += float(np.sum(state["fx"]+eps))
                            state["extra"] += count
                            state["extra_done"] += count
                            state["last_phase"] = 1 if state["extra_done"] == state["j"] else 2
                        if state["extra_done"] == state["extra_target"]:
                            state["fr" if state["positive"] else "fl"] = state["S"]/(state["j"]+state["extra_done"])
                            state["t"] += 1
                            state["phase"] = "position"
                    if time.monotonic()-last_save >= CHECKPOINT_SECONDS:
                        save()
                save()
                return _astb_result(state, model, n, rep, K, noise_keys, weight_keys, identity)
            except PrecisionRequired as error:
                # A weight has already been drawn for this rejected position.
                # Do not publish that half-advanced state as a resumable checkpoint.
                state["elapsed_seconds"] += time.monotonic()-last_save
                state["noise"] = noise.snapshot()
                state["weights"] = weights.bit_generator.state
                retry = dict(precision_digits=state["precision"], q=state["q"],
                             stage=state["t"], reason=str(error),
                             generated_normal_values=noise.generated)
                state["precision_restarts"].append(retry)
                state["retry_observations"] += state["q"]
                state["retry_generated"] += noise.generated
                next_precision = state["precision"]*2
                if next_precision > max_precision:
                    state["precision_failure"] = retry
                    failure_result = dict(n=n, q=state["q"], setting=model["setting"], replicate=int(rep),
                        status="precision_failure", estimate=None, error=None, log10_error=None,
                        tests=state["tests"], extra=state["extra"], fallback=None,
                        precision_digits=state["precision"], precision_restarts=state["precision_restarts"],
                        computational_observations=state["retry_observations"],
                        runtime_seconds=state["elapsed_seconds"], identity=identity,
                        failure_reason=str(error))
                    state["terminal_failure_result"] = failure_result
                    _save(checkpoint, identity, state)
                    return failure_result
                state = _initial_astb(next_precision, state)
                _save(checkpoint, identity, state)


def validate_runners():
    """Portable, small deterministic validation; returns JSON-ready evidence.

    These checks use a reserved phase and at most 2,000 responses per task.
    They neither select settings nor contribute observations to final results.
    The more exhaustive local tests are in test_revision_simulation.py.
    """
    import tempfile
    started = time.monotonic()
    cfg = dict(setting=3, gamma=1, A=1., sigma=.02, v=.02, delta=.05,
               theta=1/3, theta_exact="1/3", left=0., right=1.,
               left_exact="0", right_exact="1")
    checks = {}
    stb = run_stb_task(cfg, 4, grid=[10, 100, 1000], phase=902)
    checks["stb_every_budget"] = [r["q"] for r in stb["rows"]] == [10, 100, 1000]
    checks["stb_exact_geometry"] = all("exact_error" in r for r in stb["rows"])
    linear = run_astb_task(cfg, 2000, 4, phase=902)
    checks["astb_all_responses"] = linear["q"] == linear["tests"]+linear["extra"] == 2000
    checks["linear_fit_not_fallback"] = linear["fallback"] == 0
    checks["linear_expansion_identity"] = abs(linear["linear_remainder"]) < .1
    scaled = run_astb_task(dict(cfg, A=2., sigma=.04, v=.04), 2000, 4, phase=902)
    checks["amplitude_noise_scale_invariance"] = (linear["estimate"] == scaled["estimate"]
                                                  and linear["stages"] == scaled["stages"])
    jump_cfg = dict(cfg, gamma=0, initial_precision_digits=24)
    jump = run_astb_task(jump_cfg, 2000, 8, phase=902)
    high = run_astb_task(dict(jump_cfg, initial_precision_digits=jump["precision_digits"]),
                         2000, 8, phase=902)
    checks["precision_retry_matches_same_seed"] = bool(jump["precision_restarts"]) and all(
        jump[key] == high[key] for key in ("estimate", "error", "slope", "tests", "extra", "stages"))
    checks["retry_work_counted"] = jump["computational_observations"] > jump["q"] == 2000
    checks["jump_has_no_clt_claim"] = jump["standardized"] is None
    with tempfile.TemporaryDirectory() as temporary:
        path = Path(temporary)/"validation.pkl"
        first = run_astb_task(cfg, 1000, 6, path, phase=902)
        resumed = run_astb_task(cfg, 1000, 6, path, phase=902)
        checks["completed_checkpoint_stable"] = all(first[key] == resumed[key] for key in (
            "estimate", "error", "slope", "tests", "extra", "stages"))
    return dict(passed=bool(all(checks.values())), checks=checks,
        max_budget_per_task=2000, phase=902, seed=SEED, revision_domain=REVISION_DOMAIN,
        forced_jump_precision_digits=jump["precision_digits"],
        forced_jump_precision_restarts=jump["precision_restarts"],
        forced_jump_computational_observations=jump["computational_observations"],
        elapsed_seconds=time.monotonic()-started)
